name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-azure.outputs.static_web_app_url }}
    permissions:
      id-token: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build and deploy into Azure
        uses: Azure/static-web-apps-deploy@v1
        id: deploy-to-azure
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_GRASS_03A8E7C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_build_command: "npm run build:production"
          app_location: "/"
          api_location: "api"
          output_location: "dist/cash-manager-frontend/browser"

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_GRASS_03A8E7C03 }}
          app_location: "/"
          action: "close"
