name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build and deploy into Azure
        uses: Azure/static-web-apps-deploy@v1
        id: deploy-to-azure
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_GRASS_03A8E7C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_build_command: "npm run build:production"
          app_location: "/"
          api_location: "api"
          output_location: "dist/cash-manager-frontend/browser"
